planners:
  - {name: NavfnPlanner, type: "navfn_planner/NavfnPlanner"}
  - {name: genroute, type: "global_planner/SimplePlanner"}
  # - {name: SBPL, type: "SBPLLatticePlanner"}

planner_executions:
  - {name: NavfnPlanner_execution, type: "navfn_planner/NavfnPlannerExecution"}
  - {name: genroute_execution, type: "global_planner/SimplePlannerExecution"}
  # - {name: SBPL_execution, type: "SBPLLatticePlannerExecution"}