#The planner mode 0->RVIZ 1->RANDOM 2->WAYPOINTS
mode : 0

#The planner plugin to load, uncomment the planner to be used
planner : {name : "NavfnPlanner", type: "navfn_planner/NavfnPlanner" }
#planner : {name: "SBPL", type: "SBPLLatticePlanner"}
#planner : {name: "genroute", type: "global_planner/SimplePlanner"}

#The parameters used when mode is random
num_of_tests : 100 #no of tests to run
x_range : [-5.0,5.0] #the x limits used by the random number generator
y_range : [-5.0,5.0] #the y limits used by the random number generator

#The params used when waypoints are used, waypoints in the form (x,y,theta(rads))
waypoints :
  - [1.0,1.0,0]
  - [3.0,1.0,0.0]
  - [3.0,-1.0,3.14]
