global_costmap:
  global_frame: map
  update_frequency: 2.5
  publish_frequency: 2.5
  transform_tolerance: 0.5
  width: 20
  height: 20
  origin_x: -7.5
  origin_y: -7.5
  static_map: false
  rolling_window: true
  inflation_radius: 0.40
  resolution: 0.025
  plugins:
            - {name: static,                  type: "costmap_2d::StaticLayer"}
            - {name: obstacle_layer,         type: "costmap_2d::VoxelLayer"}
            - {name: inflation,               type: "costmap_2d::InflationLayer"}
